### ISSUE TITLE
Menambahkan Deskripsi Cara Menjalankan Proyek dan Tautan ke Demo Aplikasi

### ISSUE THREAD

**Issue by jefrydco** [fauzan1892/submisi_vuejs#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Fauzan. Mas juga sudah menambahkan Bootstrap sebagai kerangka kerja gayanya dan menambahkan beberapa gaya sendiri. Warna tersebut juga kebetulan salah satu warna favorit saya.

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni menambahkan deskripsi cara menjalankan proyek di bagian `readme.md` dan menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.

Semangat selalu Mas! :muscle:

**Comment by fauzan1892** [comment]
siap mas, dan terima kasih atas ilmunya yang bermanfaat beserta feedback sarannya, sukses selalu mas Jefry :smile: :pray:
